import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Nav from '../components/nav'
import sidebar from '../components/sidebar'
import Collapsible from 'react-collapsible';
import Latex from 'react-latex-next'
import Script from 'next/script'

export default function Home() {

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

      </Head>

      <main className={styles.main}>
      <script src="https://unpkg.com/@curvenote/article"></script>

        <Nav></Nav>
        <div>
          <article>
          <section >
           
            <h2>Acknowledgements</h2>
            <p>
                This site is based of a series of blog posts <a href="https://www.linkedin.com/in/adam-marblestone-87202813/">Adam Marblestone</a> initially wrote in 2019. It has been edited and extended by <a href="https://twitter.com/_neilhacker">Neil Hacker</a>. 
                <br></br><br></br>
                The content has been made immeasurably better through the good suggestions from friends including Brad Zamft, Sarah Sclarsic, Will Regan, David Pfau, David Brown, David Rolnick, Tom Hunt, Tony Pan, Marcus Sarofim, Michael Nielsen, Sam Rodriques, James Ough, Evan Miyazono, Nick Barry, Kevin Esvelt, Eric Drexler and George Church. 
            <br></br><br></br>
            <span style={{fontSize: 'medium', color: 'white'}}><Latex>{' $ ____________________________________________ $'}</Latex></span> 

            </p>
          </section>
          </article>
        </div> 

        <div class="footer">
        <p style={{fontSize: '5rem'}}><a href="../">&#8678;</a> &nbsp; <a href="../disclaimers">&#8680;</a></p>
        </div>  

      </main>

    </div>
  )
}
