import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Nav from '../components/nav'
import sidebar from '../components/sidebar'
import Collapsible from 'react-collapsible';
import Latex from 'react-latex-next'
import Script from 'next/script'

export default function Home() {

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:title" content="Climate Technology Primer"/>
        <meta name="twitter:site" content="https://www.climatetechnologyprimer.com"/>
        <meta name="twitter:description" content="A quantitiative look at the climate and the technological solutions that can help."/>
        <meta name="twitter:image" content="https://www.climatetechnologyprimer.com/public/img/twitter_card.png"/>


      </Head>

      <main className={styles.main} id='main'>
      <script src="https://unpkg.com/@curvenote/article"></script>

        <Nav></Nav>
        <div>
          <article>
          <section>
          <br></br><br></br>
          <Image src='/img/header.png'  alt="land use of various cdr approaches" width="1250px" height="500px"/>
          <h1>Climate Technology Primer</h1>
            <p>

            <label for="mn-demo0.0" class="margin-toggle">&#8853;</label>
            <input type="checkbox" id="mn-demo0.0" class="margin-toggle"/>
            <span class="marginnote" id="id_option">
            Excellent documents and courses are available online on what we are doing to the climate — such as the 
            <a href="https://www.ipcc.ch/2019/"> IPCC reports</a> or <a href="https://www.e-education.psu.edu/meteo469/">Prof. Michael Mann’s online course </a>
            or <a href="http://web.archive.org/web/20210203213718/http://web.gps.caltech.edu/classes/ese148a/NASclimatechange.pdf"> this National Academies report</a>.
            </span> 
 
            <label for="mn-demo0.1" class="margin-toggle">&#8853;</label>
            <input type="checkbox" id="mn-demo0.1" class="margin-toggle"/>
            <span class="marginnote" id="id_option">
              <br></br>
            There are integrative assessments of solutions, such as <a href="https://www.drawdown.org/">Project Drawdown</a>, and a huge proliferation of innovative technologies 
            being proposed and developed in all sectors. There are also some 
            <a href="http://newmaeweb.ucsd.edu/courses/MAE119/WI_2018/ewExternalFiles/Hoffert%20et%20al%20%282002%29%20Advanced%20Technology%20Paths%20to%20Global%20Cl.pdf"> superb review papers </a>
            that treat the need for new technologies.
            Bret Victor has a <a href="http://worrydream.com/ClimateChange/">beautiful overview</a> emphasizing the role of general design, modeling and implementation capacity, and there 
            is now a <a href="https://github.com/ron-rivest/MIT-6.S898-climate-change/blob/master/resources.md">climate change for computer scientists course</a> at MIT. And if you 
            want more of a quantitative look at things I can't reccommend David MacKay's <a href="https://www.withouthotair.com/">Sustainable Energy without the Hot Air</a> enough.
            </span> 

            <label for="mn-demo0.2" class="margin-toggle">&#8853;</label>
            <input type="checkbox" id="mn-demo0.2" class="margin-toggle"/>
            <span class="marginnote" id="id_option">
              <br></br>
            Within applications of machine learning to climate, I recommend <a href="https://arxiv.org/abs/1906.05433">this paper</a> for a broader picture that spans a wider range of solution domains — such breadth serves as good food for thought for technologists interested in finding the truly most impactful areas in which they might be able to contribute
            </span> 

            <br></br>
            Welcome to my Climate Technology Primer. Here I try to break down in a bit more of a quantitative way what is currently happening 
            to our climate and some interesting ways technology can help address these problems. These posts have a numerical bend to them and go back to the basics to try to help build up a quantitative picture of how 
            technology can contribute to solving our climate problems. They’re done from the perspective of a scientifically literate 
            (PhD in Biophysics) outsider who wants to have the foundations to do some back of the envelope looking at the challenges. 
            Hopefully they provide this, as well as links that go into even more detail. 
            <br></br><br></br>
            The emphasis of these posts is more on things I perceive to be less mainstream topics, like CDR or geo-engineering. That very much doesn’t mean that the more mainstream things, like decarbonizing steel and cement production, hydrogen, adaptation to climate effects, are any less important, they might in fact be more so. It just means that these are the things I think have had less coverage than they might warrant, and they’re some of the things I find particularly interesting. 
            <br></br><br></br>
            <b style={{fontSize: "xx-large"}}><a href="../acknowledgements">Start reading → </a></b>
            <span style={{fontSize: 'medium', color: 'white'}}><Latex>{' $ ____________________________________________ $'}</Latex></span> 

            </p>

          
          </section>
          </article>
        </div>    

      </main>

    </div>
  )
}
