import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Nav from '../components/nav'
import sidebar from '../components/sidebar'
import Collapsible from 'react-collapsible';
import Latex from 'react-latex-next'
import Script from 'next/script'

export default function Home() {

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

      </Head>

      <main className={styles.main} id='main'>
      <script src="https://unpkg.com/@curvenote/article"></script>

        <Nav></Nav>
        <div>
          <article>
          <section>
              
            <p>
            Welcome to my Climate Technology Primer. Here I try to break down in a bit more of a quantitative way what is currently happening 
            to our climate and some more interesting ways we can help address these problems.  

            </p>

          
          </section>
          </article>
        </div>    

      </main>

    </div>
  )
}
